### ISSUE TITLE
application and component versioning issue

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#326]
Continuing upon #325 , consider this scenario, when we create a few versions of an application or component from UI and then delete an in-between version of either application or component, the parent version of subsequent versions is not set correctly and the chain of versions is lost. This causes various issues going forward.

**Comment by sbtaylor15** [comment]
Fixed the reparenting on a delete for the app version and comp version.  

Image ui-skin-v9.0.0.3090-gd18917f and master-v9.0.0.2939-g2cba1b0 and going forward have the updates in place.  Fyi, same images as the API updates for the Groovy changes.

**Comment by piyush94** [comment]
Tried tag, master-v9.0.0.2940-g22a4259. The issue is still there.

**Comment by sbtaylor15** [comment]
Which one did not work, deleting a component version, app version or both.

**Comment by piyush94** [comment]
I only tried deleting an application version.

**Comment by sbtaylor15** [comment]
Can you send a screen shot of your version tree for the base application?  We need to see how the versions are related to each other.

**Comment by sbtaylor15** [comment]
You can skip the screen shot.  We believe that we found what is happening.  There are multiple ways to delete the version in the old UI and they each call a different method on the backend.

**Comment by sbtaylor15** [comment]
Here is the image with the update  master-v9.0.0.2941-ga4d91ba.  Looks like only the old UI had this issue.  Components versions in the old UI had the same issue. Fixed as well.

**Comment by piyush94** [comment]
Thanks, it's working for both application and component versions.
